Repository Dembrane/echo, pull requests merged in 2025-08, with the labels that each got.

#257 ECHO-342 add report edit feature
  echo/frontend/package.json
  echo/frontend/pnpm-lock.yaml
  echo/frontend/src/App.tsx
  echo/frontend/src/components/report/ReportEditor.tsx
  echo/frontend/src/components/report/ReportRenderer.tsx
  echo/frontend/src/locales/de-DE.po
  echo/frontend/src/locales/de-DE.ts
  echo/frontend/src/locales/en-US.po
  echo/frontend/src/locales/en-US.ts
  echo/frontend/src/locales/es-ES.po
  echo/frontend/src/locales/es-ES.ts
  echo/frontend/src/locales/fr-FR.po
  echo/frontend/src/locales/fr-FR.ts
  echo/frontend/src/locales/nl-NL.po
  echo/frontend/src/locales/nl-NL.ts
  echo/frontend/src/routes/project/report/ProjectReportRoute.tsx
Labels: Feature, improvement

#261 ECHO-408 Conversation name not being shown in segment for library
  echo/frontend/src/components/library/hooks/index.ts
  echo/frontend/src/components/quote/Quote.tsx
Labels: bug

#262 ECHO-378 "Request Access" instead of "Contact sales"
  echo/frontend/src/components/conversation/AutoSelectConversations.tsx
  echo/frontend/src/locales/de-DE.po
  echo/frontend/src/locales/de-DE.ts
  echo/frontend/src/locales/en-US.po
  echo/frontend/src/locales/en-US.ts
  echo/frontend/src/locales/es-ES.po
  echo/frontend/src/locales/es-ES.ts
  echo/frontend/src/locales/fr-FR.po
  echo/frontend/src/locales/fr-FR.ts
  echo/frontend/src/locales/nl-NL.po
  echo/frontend/src/locales/nl-NL.ts
  echo/frontend/src/routes/project/library/ProjectLibrary.tsx
Labels: improvement

#266 ECHO-415 Chat and conversation changes
  echo/frontend/src/components/chat/ChatAccordion.tsx
  echo/frontend/src/components/chat/ChatSkeleton.tsx
  echo/frontend/src/components/chat/hooks/index.ts
  echo/frontend/src/components/conversation/ConversationAccordion.tsx
  echo/frontend/src/components/conversation/hooks/index.ts
  echo/frontend/src/locales/de-DE.po
  echo/frontend/src/locales/de-DE.ts
  echo/frontend/src/locales/en-US.po
  echo/frontend/src/locales/en-US.ts
  echo/frontend/src/locales/es-ES.po
  echo/frontend/src/locales/es-ES.ts
  echo/frontend/src/locales/fr-FR.po
  echo/frontend/src/locales/fr-FR.ts
  echo/frontend/src/locales/nl-NL.po
  echo/frontend/src/locales/nl-NL.ts
Labels: Feature, improvement

#273 ECHO-438 remove the tooltip that says 'audio recording will be deleted'
  echo/frontend/src/routes/project/conversation/ProjectConversationTranscript.tsx
Labels: improvement
