Repository Dembrane/echo, pull requests merged in 2025-10, with the labels that each got.

#318 ECHO-465 Non-blocking uploads with presigned URLs + Kubernetes worker optimization
  .gitignore
  echo/frontend/src/config.ts
  echo/frontend/src/lib/api.ts
  echo/server/dembrane/api/participant.py
  echo/server/dembrane/ner.py
  echo/server/dembrane/quote_utils.py
  echo/server/dembrane/s3.py
  echo/server/dembrane/service/conversation.py
  echo/server/prod-worker-cpu.sh
  echo/server/prod-worker.sh
  echo/server/prod.sh
  echo/server/pyproject.toml
  echo/server/requirements-dev.lock
  echo/server/requirements.lock
  echo/server/run-worker-cpu.sh
  echo/server/run-worker.sh
Labels: Feature, improvement

#322 RAG ETL Performance Improvements: Parallel LLM, Batch Processing & Bug Fixes
  echo/server/dembrane/api/stateless.py
  echo/server/dembrane/audio_lightrag/main/__init__.py
  echo/server/dembrane/audio_lightrag/main/run_etl.py
  echo/server/dembrane/audio_lightrag/pipelines/audio_etl_pipeline.py
  echo/server/dembrane/audio_lightrag/pipelines/contextual_chunk_etl_pipeline.py
  echo/server/dembrane/audio_lightrag/pipelines/directus_etl_pipeline.py
  echo/server/dembrane/audio_lightrag/services/__init__.py
  echo/server/dembrane/audio_lightrag/services/contextualizer.py
  echo/server/dembrane/audio_lightrag/tests/__init__.py
  echo/server/dembrane/audio_lightrag/tests/conftest.py
  echo/server/dembrane/audio_lightrag/tests/e2e_test.py
  echo/server/dembrane/audio_lightrag/tests/unit_tests/__init__.py
  echo/server/dembrane/audio_lightrag/tests/unit_tests/audio_etl_pipeline_test.py
  echo/server/dembrane/audio_lightrag/tests/unit_tests/contextual_chunk_etl_pipeline_test.py
  echo/server/dembrane/audio_lightrag/tests/unit_tests/directus_etl_pipeline_test.py
  echo/server/dembrane/audio_lightrag/tests/unit_tests/neo4j_test.py
  echo/server/dembrane/audio_lightrag/utils/async_utils.py
  echo/server/dembrane/audio_lightrag/utils/audio_utils.py
  echo/server/dembrane/audio_lightrag/utils/azure_utils.py
  echo/server/dembrane/audio_lightrag/utils/litellm_utils.py
  echo/server/dembrane/audio_lightrag/utils/process_tracker.py
  echo/server/dembrane/audio_lightrag/utils/prompts.py
  echo/server/dembrane/conversation_utils.py
  echo/server/dembrane/scheduler.py
  echo/server/dembrane/tasks.py
  echo/server/run-worker-cpu.sh
  echo/server/scripts/simple_rag_observer.py
  echo/server/scripts/test_rag_query.py
  echo/server/scripts/test_trigger_directus_etl.py
Labels: bug, Feature, improvement

#317 ECHO-497 Smart Auto Select
  echo/frontend/src/components/chat/Sources.tsx
  echo/frontend/src/components/conversation/AutoSelectConversations.tsx
  echo/frontend/src/components/conversation/ConversationAccordion.tsx
  echo/frontend/src/routes/project/chat/ProjectChatRoute.tsx
  echo/server/dembrane/api/chat.py
  echo/server/dembrane/chat_utils.py
  echo/server/prompt_templates/auto_select_conversations.de.jinja
  echo/server/prompt_templates/auto_select_conversations.en.jinja
  echo/server/prompt_templates/auto_select_conversations.es.jinja
  echo/server/prompt_templates/auto_select_conversations.fr.jinja
  echo/server/prompt_templates/auto_select_conversations.nl.jinja
  echo/server/prompt_templates/is_followup_question.de.jinja
  echo/server/prompt_templates/is_followup_question.en.jinja
  echo/server/prompt_templates/is_followup_question.es.jinja
  echo/server/prompt_templates/is_followup_question.fr.jinja
  echo/server/prompt_templates/is_followup_question.nl.jinja
Labels: Feature, improvement

#319 ECHO-503 Scroll to QR code section mobile
  echo/frontend/src/components/conversation/ConversationAccordion.tsx
  echo/frontend/src/components/project/ProjectAccordion.tsx
  echo/frontend/src/components/project/ProjectSidebar.tsx
Labels: improvement
