Repository Dembrane/echo, pull requests merged in 2025-07, with the labels that each got.

#212 echo-340-bug-etl-pl-not-being-triggered
  echo/server/dembrane/tasks.py
Labels: Feature

#225 fix report and library
  echo/frontend/src/lib/api.ts
  echo/frontend/src/routes/project/conversation/ProjectConversationTranscript.tsx
  echo/server/dembrane/api/project.py
  echo/server/dembrane/report_utils.py
Labels: Feature

#239 ECHO-368 Add conversation links
  echo/directus/sync/collections/permissions.json
  echo/directus/sync/collections/policies.json
  echo/frontend/src/components/conversation/ConversationLink.tsx
  echo/frontend/src/components/conversation/hooks/index.ts
  echo/frontend/src/config.ts
  echo/frontend/src/lib/typesDirectus.d.ts
  echo/frontend/src/locales/de-DE.po
  echo/frontend/src/locales/de-DE.ts
  echo/frontend/src/locales/en-US.po
  echo/frontend/src/locales/en-US.ts
  echo/frontend/src/locales/es-ES.po
  echo/frontend/src/locales/es-ES.ts
  echo/frontend/src/locales/fr-FR.po
  echo/frontend/src/locales/fr-FR.ts
  echo/frontend/src/locales/nl-NL.po
  echo/frontend/src/locales/nl-NL.ts
  echo/frontend/src/routes/project/conversation/ProjectConversationOverview.tsx
Labels: Feature, improvement

#232 ETL hot fixes
  echo/server/dembrane/audio_lightrag/main/run_etl.py
  echo/server/dembrane/audio_lightrag/pipelines/audio_etl_pipeline.py
  echo/server/dembrane/audio_lightrag/pipelines/contextual_chunk_etl_pipeline.py
  echo/server/dembrane/audio_lightrag/pipelines/directus_etl_pipeline.py
  echo/server/dembrane/audio_lightrag/utils/echo_utils.py
  echo/server/dembrane/audio_lightrag/utils/lightrag_utils.py
Labels: bug, improvement

#248 ECHO-372 Fix conversation summary
  echo/frontend/src/routes/project/conversation/ProjectConversationOverview.tsx
Labels: bug

#251 Update dependency references for Directus SDK in configuration files
  echo/server/dembrane/directus.py
  echo/server/json_templates/default_view_recurring_themes.en.jinja
  echo/server/pyproject.toml
  echo/server/requirements-dev.lock
  echo/server/requirements.lock
Labels: Feature

#255 Project list render bug on search fix
  echo/frontend/src/routes/project/ProjectsHome.tsx
Labels: improvement
